name: Node.js CI
on:
  push:
    branches: [main, lint-github-actions]
  pull_request:
    branches: [main, lint-github-actions]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        # uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        working-directory: client
        run: |
          npm ci
          npm run lint
